# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzZiZTc0ZjEwMjg5Yzg0MDNlMTNiNzAxMGI3Y2U4MDliYWVkOTQ4NzU2NTJkODI2NzVjMWQ4NTFhMWYzYjRmYmJkNzAxMTdjYzQ2NGIyZmZiMDhmNmJiNTY3ZmVlMzkyNDhlMTNjZTczNDFjNmZmNGRiYzFiY2VjMDdkZDY4OTc=
