# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OWE3YjM2YjljOGRmZjI0ODUxMWNjMmQ1ZGM2MTY3NmViZWQ5YTBhMGM5MWY4YjQ3NTAzNTViOGQ5Yjc2YTE3NjkzYzcwNmJkYTgxODYzY2M1MWJhZjFjYjQ1MmY5ZTI3YjFiYjY1OWZkYzAzNzI5ZTU4YzFiYzZjYmRlMjM0YWI=
